DROP PROCEDURE IF EXISTS save_stats_computation(UUID, JSONB, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BOOLEAN, BOOLEAN, BOOLEAN, TEXT);
DROP PROCEDURE IF EXISTS save_qr_computation(UUID, JSONB, JSONB, JSONB, BOOLEAN, TEXT);
DROP PROCEDURE IF EXISTS delete_refresh_token(TEXT);
DROP PROCEDURE IF EXISTS save_refresh_token(UUID, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS get_refresh_token(TEXT);
DROP FUNCTION IF EXISTS get_user_by_email(TEXT);
